feat: implement bibtex logic in Reference.save()
acdh-oeaw/apis-bibsonomy pull request #32
Opened 2023-05-09 12:50 UTC by b1rger

The logic to fill the bibtex data should be part of the `save()` method
of the Reference model. This way anywhere an instance is saved, the
bibtex data is fetched.
The logic is copied from the api_views.SaveBibsonomyEntry.post() method
and refactored a bit.

2023-05-17 12:57 UTC, gregorpirgie commented on apis_bibsonomy/models.py
> +                bib_e = BibsonomyEntry(bib_hash=bib_ref, base_set=sett1)
sett1 is not defined here, see this snippet for comparison:

[```python 
   sett = getattr(settings, "APIS_BIBSONOMY", [])
        for s in sett:
            if "url" in s.keys():
                if s["url"] in bib_ref:
                    sett1 = s
                    kind = s["type"]
        if bib_ref is not None:
            r = {"bibs_url": bib_ref}
            if kind == "bibsonomy":
                bib_e = BibsonomyEntry(bib_hash=bib_ref, base_set=sett1)
```](https://github.com/acdh-oeaw/apis-bibsonomy/blob/878eff3382dd4da74aed33db8417fc872582cffc/apis_bibsonomy/api_views.py#L31C3-L52)

2023-05-17 13:24 UTC, gregorpirgie requested changes
I would halt this change at the moment, but I follow the basic reasoning to move the logic  from the api_view.py post-method to the save method here. I would suggest to: 
- implement this update here with a refactor of the api_view.py post-method to get rid of redundancies
- and also consider to refactor both with an implementation of an update logic of existing entries. See #22 .

2023-05-17 13:24 UTC, gregorpirgie commented on apis_bibsonomy/models.py
> +        bib_ref = self.bibs_url
bib_ref is defined here but not used (you reference self.bibs_url beneath, where you could use bib_ref.

2023-05-17 13:24 UTC, gregorpirgie commented on apis_bibsonomy/models.py
> +        sources = [s for s in sources if s.get("url") and s.get("url") in self.bibs_url]
```suggestion
        sources = [s for s in sources if s.get("url") and s.get("url") in bib_ref]
```

2023-05-17 13:24 UTC, gregorpirgie commented on apis_bibsonomy/models.py
> +        if self.bibs_url is not None:
```suggestion
        if  bib_ref is not None:
```

2023-05-17 13:24 UTC, gregorpirgie commented on apis_bibsonomy/models.py
> +        super().save()
Shouldn't this line be indented to only save the object if the object actually has a bibs-ref and therefore a referenced object?  And / or raise an error if bibs-ref is missing?

2023-05-17 14:52 UTC, b1rger commented on apis_bibsonomy/models.py
> +    def save(self):
Yes, you're right - i've no added a check for the `bibtex` attribute, so the fetch only is done if it is actually empty

2023-05-17 15:44 UTC, b1rger commented
> I would halt this change at the moment, but I follow the basic reasoning to move the logic from the api_view.py post-method to the save method here.

We need this functionality in a project - we want to create Reference instances without using the API endpoint.

>    * implement this update here with a refactor of the api_view.py post-method to get rid of redundancies

You're right - I tried to make the change as small as possible, but it makes sense to clean up the other parts to remove redundancies. I've now moved the functionality of fetching the bibtex information to the `utils` module and it is being used in the `save()` method as well as the `apis_views` post request.

>    * and also consider to refactor both with an implementation of an update logic of existing entries. See [Add edit button in tooltip references table #22](https://github.com/acdh-oeaw/apis-bibsonomy/issues/22) .

I think a separate edit view is out of scope of this PR, but I agree that this should be implemented at some point.

> Ideally, we would write a test case to accompany these changes, as they touch core functionality of the module.

I'll have a look if there are public API endpoints to test the `bibtex` fetching.

2023-05-18 16:36 UTC, gregorpirgie approved these changes

2023-05-22 08:45 UTC, merged